services:
  nginx:
    build:
      context: ./docker/development/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api:/app
      - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: ./docker/development/php-fpm
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=api.task-manager
    user: "1000:1000"
    volumes:
      - ./api:/app
      - ./docker/development/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - postgres
    networks:
      - app-network

  php-cli:
    build:
      context: ./docker/development/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./docker/development/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: task-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
